name: pop

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["525 530 1", "525 530 2", "525 530 3", "525 530 4", "525 530 5", "525 530 6", "525 530 7", "530 535 8", "530 535 9", "530 535 10", "530 535 11", "530 535 12", "530 535 13", "530 535 14", "535 540 15", "535 540 16", "535 540 17", "535 540 18", "535 540 19", "535 540 20", "535 540 21"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Dependencies
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Depedencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        chmod +x ./setup.sh && ./setup.sh
        sleep 5
        ls -l
    - name: Your current IP address
      run: curl -s http://ipecho.net/plain
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: ./con.ovpn
        echo_config: "false"
        username: "p0682977"
        password: "PDtGY4Fj7D"
    - name: Your vpn IP address
      run: curl -s http://ipecho.net/plain
    - name: Run
      run: |
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run-n-login.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit